# - http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# - https://github.com/spring-cloud/spring-cloud-config/blob/d9113a417dccff271744be3a4039e270b0cebd76/docs/src/main/asciidoc/spring-cloud-config.adoc#quick-start
# - https://github.com/spring-cloud/spring-cloud-consul/blob/master/docs/src/main/asciidoc/spring-cloud-consul.adoc
# - https://github.com/spring-cloud/spring-cloud-netflix/blob/8fb89b25d955fe175410853cea3b09333ef32d74/docs/src/main/asciidoc/spring-cloud-netflix.adoc
# - https://github.com/Netflix
# - https://github.com/Netflix/Hystrix/wiki/Configuration#intro
# - https://github.com/Netflix/eureka/wiki/Configuring-Eureka
# - https://github.com/Netflix/Turbine/wiki/Configuration-(1.x)


#-----------------------------------------------------------------------------------------------
# PROFILE LOCAL
#-----------------------------------------------------------------------------------------------
spring:
  profiles: local
#-----------------------------------------------------------------------------------------------
# KAFKA
#-----------------------------------------------------------------------------------------------
# see https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#consumer-groups
# see https://docs.spring.io/autorepo/docs/spring-cloud-stream-binder-kafka-docs/1.1.0.M1/reference/htmlsingle/
spring.cloud.stream:
  instanceCount: 1 # The number of deployed instances of an application. Must be set for partitioning and if using Kafka.
  #instanceIndex: # The instance index of the application: a number from 0 to instanceCount-1. Used for partitioning and with Kafka.
  #dynamicDestinations: A list of destinations that can be bound dynamically (for example, in a dynamic routing scenario). If set, only listed destinations can be bound. Default: empty (allowing any destination to be bound).
  defaultBinder: kafka # The default binder to use, if multiple binders are configured. See Multiple Binders on the Classpath.
  overrideCloudConnectors: false # This property is only applicable when the cloud profile is active and Spring Cloud Connectors are provided with the application. If the property is false (the default), the binder will detect a suitable bound service
#spring.cloud.stream.default:
#  content-type: application/json # The content type of the channel.
spring.cloud.stream.bindings:
  foo_channel_output: # The channel
    destination: messagetype.datasetname.dataname # The target destination of a channel on the bound middleware (e.g., the RabbitMQ exchange or Kafka topic).
    content-type: application/json # The content type of the channel.
    binder: kafka # The binder used by this binding. See Multiple Binders on the Classpath for details.
    producer:
      #partitionKeyExpression: # A SpEL expression that determines how to partition outbound data. If set, or if partitionKeyExtractorClass is set, outbound data on this channel will be partitioned, and partitionCount must be set to a value greater than 1 to be effective. The two options are mutually exclusive. See Partitioning Support.
      #partitionKeyExtractorClass: A PartitionKeyExtractorStrategy implementation. If set, or if partitionKeyExpression is set, outbound data on this channel will be partitioned, and partitionCount must be set to a value greater than 1 to be effective. The two options are mutually exclusive. See Partitioning Support.
      #partitionSelectorClass: A PartitionSelectorStrategy implementation. Mutually exclusive with partitionSelectorExpression. If neither is set, the partition will be selected as the hashCode(key) % partitionCount, where key is computed via either partitionKeyExpression or partitionKeyExtractorClass.
      #partitionSelectorExpression: A SpEL expression for customizing partition selection. Mutually exclusive with partitionSelectorClass. If neither is set, the partition will be selected as the hashCode(key) % partitionCount, where key is computed via either partitionKeyExpression or partitionKeyExtractorClass.
      partitionCount: 1 # The number of target partitions for the data, if partitioning is enabled.
      #requiredGroups: # A comma-separated list of groups to which the producer must ensure message delivery even if they start after it has been created
      headerMode: embeddedHeaders # When set to raw, disables header embedding on output. Effective only for messaging middleware that does not support message headers natively and requires header embedding. Useful when producing data for non-Spring Cloud Stream applications.
      useNativeEncoding: false # When set to true, the outbound message is serialized directly by client library, which must be configured correspondingly (e.g. setting an appropriate Kafka producer value serializer).
      #errorChannelEnabled: # When set to true, if the binder supports async send results; send failures will be sent to an error channel for the destination. See Message Channel Binders and Error Channels for more information.
  foo_channel_input:
    destination: messagetype.datasetname.dataname # The target destination of a channel on the bound middleware (e.g., the RabbitMQ exchange or Kafka topic).
    group: group-1 # The consumer group of the channel. Applies only to inbound bindings. See Consumer Groups.
    content-type: application/x-java-object;type=com.sample.springcloudstream.dto.FooDTO
    binder: kafka # The binder used by this binding. See Multiple Binders on the Classpath for details.
    consumer:
      concurrency: 1 # The concurrency of the inbound consumer. default 1
      partitioned: true # Whether the consumer receives data from a partitioned producer. Default: false.
      headerMode: embeddedHeaders # When set to raw, disables header parsing on input. Effective only for messaging middleware that does not support message headers natively and requires header embedding. Useful when inbound data is coming from outside Spring Cloud Streamapplications. efault: embeddedHeaders.
      maxAttempts: 3 # If processing fails, the number of attempts to process the message (including the first). Set to 1 to disable retry. Default: 3.
      backOffInitialInterval: 1000 # The backoff initial interval on retry. Default: 1000.
      backOffMaxInterval: 10000 # The maximum backoff interval. Default: 10000.
      backOffMultiplier: 2.0 # The backoff multiplier. Default: 2.0.
      instanceIndex: -1 # When set to a value greater than equal to zero, allows customizing the instance index of this consumer (if different from spring.cloud.stream.instanceIndex). When set to a negative value, it will default to spring.cloud.stream.instanceIndex. Default: -1.
      instanceCount: -1 # When set to a value greater than equal to zero, allows customizing the instance count of this consumer (if different from spring.cloud.stream.instanceCount). When set to a negative value, it will default to spring.cloud.stream.instanceCount. Default: -1.
spring.cloud.stream.kafka.bindings:
  foo_channel_output: # The channel
    producer:
      bufferSize: 33554432 # Upper limit, in bytes, of how much data the Kafka producer will attempt to batch before sending
      sync: false # Whether the producer is synchronous.
      batchTimeout: 1000 # How long the producer will wait before sending in order to allow more messages to accumulate in the same batch.
      #messageKeyExpression: # A SpEL expression evaluated against the outgoing message used to populate the key of the produced Kafka message. For example headers.key or payload.myKey. Default: none.
      configuration: # Map with a key/value pair containing generic Kafka producer properties Default: Empty map.
        max:
          request:
            size: 999999999
spring.cloud.stream.kafka.binder:
  brokers: localhost # A list of brokers to which the Kafka binder will connect.
  defaultBrokerPort: 9092 # This sets the default port when no port is configured in the broker list
  zkNodes: localhost # A list of ZooKeeper nodes to which the Kafka binder can connect.
  defaultZkPort: 2181 # This sets the default port when no port is configured in the node list
  #configuration: # Key/Value map of client properties (both producers and consumer) passed to all clients created by the binder. Due to the fact that these properties will be used by both producers and consumers, usage should be restricted to common properties, especially security settings. Default: Empty map.
  headers: x-retries #  The list of custom headers that will be transported by the binder. Default: empty.
  healthTimeout: 60 # The time to wait to get partition information in seconds; default 60. Health will report as down if this timer expires.
  offsetUpdateTimeWindow: 10000 # The frequency, in milliseconds, with which offsets are saved. Ignored if 0.
  offsetUpdateCount: 0 # The frequency, in number of updates, which which consumed offsets are persisted. Ignored if 0. Mutually exclusive with offsetUpdateTimeWindow
  requiredAcks: 1 # The number of required acks on the broker.
  minPartitionCount: 1 # Effective only if autoCreateTopics or autoAddPartitions is set
  replicationFactor: 1 # The replication factor of auto-created topics if autoCreateTopics is active.
  autoCreateTopics: true # If set to true, the binder will create new topics automatically.
  autoAddPartitions: true # If set to true, the binder will create add new partitions if required
  socketBufferSize: 1000000000 # Size (in bytes) of the socket buffer to be used by the Kafka consumers
spring.cloud.sleuth:
  json:
    enabled: false


#-----------------------------------------------------------------------------------------------
# Logging configuration
#-----------------------------------------------------------------------------------------------
logging:
  level:
    org.springframework: WARN
    com.sample: DEBUG
  pattern:
    console: '%highlight{%-5p|%d{ISO8601}{GMT}|trace=%X{X-B3-TraceId},span=%X{X-B3-SpanId}|%c{1}|%m%ex%n}{FATAL=red blink, ERROR=red, WARN=yellow bold, INFO=blue bold, DEBUG=green bold, TRACE=blue}'
    file: '%-5p|%d{ISO8601}{GMT}|trace=%X{X-B3-TraceId},span=%X{X-B3-SpanId}|%c{1}|%m%ex%n'
  config: classpath:log4j2-local.xml
